version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ampligo-agent
    main: ./main.go
    binary: ampligo-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
    files:
      - agent.example.yml
      - ampligo-agent.service
      - install.sh
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: maventama
    name: ampligo-agent
